spring.application.name=iot-backend

mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=iot-backend-client
mqtt.topic.prefix=esp/sensores/#
mqtt.qos=1  

# MongoDB
spring.mongodb.uri=mongodb://root:secret@localhost:27017/iot_db?authSource=admin
